"""Durable optional external-vector outbox; PostgreSQL remains authoritative."""

from collections.abc import Sequence

from alembic import op

revision: str = "006"
down_revision: str | None = "005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

DDL_0 = """
CREATE TABLE memory_vector_index_state (
    vector_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL, memory_id uuid NOT NULL,
    revision bigint NOT NULL DEFAULT 1, indexed_revision bigint NOT NULL DEFAULT 0,
    state text NOT NULL DEFAULT 'pending', attempts integer NOT NULL DEFAULT 0,
    last_error text, updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_vector_state_tenant_memory UNIQUE (tenant_id, memory_id),
    CHECK (state IN ('pending', 'failed', 'indexed', 'absent'))
)
"""

DDL_1 = """

CREATE OR REPLACE FUNCTION memory_vector_enqueue() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE t uuid; m uuid;
BEGIN
    IF TG_OP = 'DELETE' THEN t := OLD.tenant_id; m := OLD.memory_id;
    ELSE t := NEW.tenant_id; m := NEW.memory_id; END IF;
    EXECUTE format('INSERT INTO %I.memory_vector_index_state
        (tenant_id, memory_id) VALUES ($1, $2)
        ON CONFLICT (tenant_id, memory_id) DO UPDATE SET
        revision = memory_vector_index_state.revision + 1,
        state = ''pending'', attempts = 0, last_error = NULL, updated_at = now()',
        TG_TABLE_SCHEMA) USING t, m;
    RETURN NULL;
END;
$$;

"""

DDL_2 = """

CREATE TRIGGER memory_vector_enqueue_trigger
AFTER INSERT OR DELETE OR UPDATE OF content, embedding, embedding_model_version,
    index_status, status, trust_level, memory_type, valid_from, valid_to
ON memory_records FOR EACH ROW EXECUTE FUNCTION memory_vector_enqueue()

"""

DDL_3 = """

INSERT INTO memory_vector_index_state (tenant_id, memory_id)
SELECT tenant_id, memory_id FROM memory_records
ON CONFLICT (tenant_id, memory_id) DO NOTHING

"""


def upgrade() -> None:
    op.execute(DDL_0)
    op.execute(DDL_1)
    op.execute(DDL_2)
    op.execute(DDL_3)


def downgrade() -> None:
    op.execute("DROP TRIGGER memory_vector_enqueue_trigger ON memory_records")
    op.execute("DROP FUNCTION memory_vector_enqueue()")
    op.drop_table("memory_vector_index_state")
